apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalabit-challenge-api
  labels:
    app: scalabit-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalabit-challenge-api
  template:
    metadata:
      labels:
        app: scalabit-challenge-api
    spec:
      containers:
        - name: api
          image: scalabit-challenge-api:latest
          imagePullPolicy: Never # Use Local Image
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: github-creds
          readinessProbe:
            httpGet:
              path: /health
              port: 8080