apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
  labels:
    app: devsecops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: api
          image: devsecops-api:latest
          imagePullPolicy: Never # Use Local Image
          ports:
            - containerPort: 8080
          env:
            # Empty Variables for Now
            - name: GITHUB_TOKEN
              value: ""
            - name: GITHUB_OWNER
              value: "NunoVz"
            - name: GITHUB_REPO
              value: "Scalabit-Challenge"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080