name: CD - Deploy to Minikube

on:
  push:
    branches: [ develop, main ]

jobs:
  deploy:
    name: Build & Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t scalabit-challenge-api:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Verify Deployment
        run: |
          # Wait for Heath Check
          kubectl rollout status deployment/scalabit-challenge-api --timeout=90s