name: CI/CD - PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-sec:
    name: Lint & Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'

      # 1. Linter Go
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

      # 2. SAST
      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'

      - name: Run Tests
        run: go test -v -race -cover ./...

  deploy:
    name: Build & Deploy to Minikube
    needs: [lint-and-sec, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t scalabit-challenge-api:latest .

      - name: Create/Update Kubernetes Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          kubectl create secret generic github-creds \
            --from-literal=GITHUB_TOKEN=${GITHUB_TOKEN} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/scalabit-challenge-api --timeout=90s || (kubectl get pods && kubectl logs -l app=scalabit-challenge-api && exit 1)